// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2jXgsWiSpdnf6rETL4b9FlAJvpbNVwEI',
    appId: '1:333103814683:web:c8941d45006c857e3fc0be',
    messagingSenderId: '333103814683',
    projectId: 'ubitec-app',
    authDomain: 'ubitec-app.firebaseapp.com',
    storageBucket: 'ubitec-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCWYkNR5n5d8R2j7XoPoMpCzEHZ1AEksY',
    appId: '1:333103814683:android:e28f72febb4c39c93fc0be',
    messagingSenderId: '333103814683',
    projectId: 'ubitec-app',
    storageBucket: 'ubitec-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQsJWRs9YPyZvtOa75zPwO22HWXnkHbLA',
    appId: '1:333103814683:ios:341dc239356d96753fc0be',
    messagingSenderId: '333103814683',
    projectId: 'ubitec-app',
    storageBucket: 'ubitec-app.appspot.com',
    iosClientId: '333103814683-6uvbn5fqp2f2qp5t7rlk7t20hkg9bt3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.rastreoPaquetesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQsJWRs9YPyZvtOa75zPwO22HWXnkHbLA',
    appId: '1:333103814683:ios:341dc239356d96753fc0be',
    messagingSenderId: '333103814683',
    projectId: 'ubitec-app',
    storageBucket: 'ubitec-app.appspot.com',
    iosClientId: '333103814683-6uvbn5fqp2f2qp5t7rlk7t20hkg9bt3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.rastreoPaquetesApp',
  );
}
